FROM scratch AS ctx
COPY build_files /
COPY cosign.pub /cosign.pub

FROM ghcr.io/ublue-os/bluefin-dx-nvidia-open:stable

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/common.sh && /ctx/desktop-nvidia.sh

RUN bootc container lint